### ISSUE TITLE
Syntax highlighting example

### ISSUE THREAD

**Issue by rexwebmedia** [remarkjs/react-remark#51]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Not working with remark-prism.

### Solution

Any lightweight syntax highlighter support.

### Alternatives

Can't find any alternatives.

**Comment by Murderlon** [comment]
There is not enough information to help. "Not working with remark-prism" is not an helpful issue. Please refer to [asking quality questions](https://github.com/unifiedjs/.github/blob/main/support.md#asking-quality-questions).

In the meantime, I recommend taking a look at this example with `react-markdown`: https://github.com/remarkjs/react-markdown#use-custom-components-syntax-highlight. The `components` prop from that package is similar to `rehypeReactOptions.components` from this package so it could serve as inspiration. Alternatively, switch to `react-markdown` and use that example.

**Comment by rexwebmedia** [comment]
Here's a minimal example
https://stackblitz.com/edit/nextjs-sfulsg?file=pages/index.js

**Comment by wooorm** [comment]
This is a bug in that plugin. Raise it there. They have several open issues, perhaps it is already reported.

You initially mentioned “Any lightweight syntax highlighter support.” as a solution you are looking for. I believe `remark-prism` isn’t that. Perhaps you should use the highligher we maintain: https://github.com/rehypejs/rehype-highlight. Or https://github.com/mapbox/rehype-prism if you want prism.
