### ISSUE TITLE
Custom components error

### ISSUE THREAD

**Issue by imclint21** [remarkjs/react-remark#75]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

Use `rehypeReactOptions`

### Expected behavior

I'm interested by create custom components like this:

```jsx
components: {
    "interactive-counter": Counter
}
```

### Actual behavior

Seems than custom components does not work, and give an empty <p></p>

**Comment by ChristianMurphy** [comment]
react-remark, rehype-react, react-markdown, and mdx all support custom instrinsic elements through extensions of the React intrinsic.
You can find more on that here: https://goulet.dev/posts/consuming-web-component-react-typescript/

**Comment by imclint21** [comment]
I see, but there no simple way to create custom components using remark without creating intrinsic components?

**Comment by ChristianMurphy** [comment]
If you want strong TypeScript types, no.
You need to type your custom elements.

Without TypeScript sure, as long as it's a valid HTML custom element it should work.

If you want custom elements in the JSX sense, then you would want/need https://mdxjs.com/
